/*.$file${..\src\aos::qmodel.h} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*
* Model: qmodel.qm
* File:  ${..\src\aos::qmodel.h}
*
* This code has been generated by QM 5.1.4 <www.state-machine.com/qm/>.
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*/
/*.$endhead${..\src\aos::qmodel.h} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
#ifndef QMODEL_H
#define QMODEL_H

/* define the event signals used in the application ------------------------*/
enum QModelSignals
{
    TEST_SIG = Q_USER_SIG,  // offset the first signal by Q_USER_SIG (4)
    /* insert other published signals above ... */
    MAX_PUB_SIG,                // the last published signal
    TIMEOUT_SIG,
    MAX_SIG                     //keep last (the number of signals) */
};

/* product behaviour active object(s) used in this application -------------------------------*/

/*.$declare${Shared} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/

/* opaque AO pointer */
extern QActive* const AO_Blinky;
/*.${Shared::Blinky_ctor_call} .............................................*/
void Blinky_ctor_call(void);
/*.$enddecl${Shared} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/

#endif // QMODEL_H